@user_id = 1

### 
PUT https://localhost/api/v1/users/{{user_id}} HTTP/1.1
content-type: application/json
accept: application/json

{    
    "email": "{{Math.floor(+new Date/1e3)}}@mail.ch",
    "firstname": "BillX",
    "lastname": "BarX",
    "password": "passwordX",
    "organisation": "BarX Organisation",
    "role": "ROLE_FOO_BAR"
}