services:
  
  nginx:
    build:
      target: dev
    volumes:
      - ./.docker/nginx/local.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    environment:
      - DB_PASSWORD=

  postgres:
    environment:
      - POSTGRES_PASSWORD=password

  adminer:
    container_name: pff-api-adminer
    image: adminer 
    restart: always
    ports:
      - 8080:8080