services:
  nginx:
    container_name: pff-api-nginx
    restart: always
    build: 
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build: ./.docker/php-fpm
    container_name: pff-api-php
    environment:
      - DOCKER=1
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
    volumes:
      - ./app:/var/www/html
    links:
      - postgres

  postgres:
    container_name: pff-api-postgres
    image: postgres:16.1
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
